 
-- tícket médio de todas as vendas no dia anterior
SELECT TNF.DATA_EMISSAO ,
		AVG(TNF.VALOR_TOTAL) AS TICKET_MEDIO
FROM TB_NOTA_FISCAL TNF 
WHERE TNF.DATA_EMISSAO = SUBDATE(CURDATE(), 1)  ;


-- tícket médio de todas as vendas na semana corrente (sete dias para trás a partir do dia de ontem)
SELECT TNF.DATA_EMISSAO ,
		AVG(TNF.VALOR_TOTAL) AS TICKET_MEDIO
FROM TB_NOTA_FISCAL TNF 
WHERE TNF.DATA_EMISSAO BETWEEN SUBDATE(CURDATE(), 8) AND SUBDATE(CURDATE(), 1) ;


-- tícket médio de todas as vendas no mês corrente (do dia 1 do mês corrente até o dia de ontem)
SELECT TNF.DATA_EMISSAO ,
		AVG(TNF.VALOR_TOTAL) AS TICKET_MEDIO
FROM TB_NOTA_FISCAL TNF 
WHERE TNF.DATA_EMISSAO BETWEEN DATE_FORMAT(CURDATE(),'%Y-%m-01') AND SUBDATE(CURDATE(), 1) ;


-- tícket médio das vendas Web no dia anterior
SELECT TP.DATA_COMPRA ,
		AVG(TP.VALOR_TOTAL) AS TICKET_MEDIO 
FROM TB_PEDIDO TP 
WHERE TP.DATA_COMPRA = SUBDATE(CURDATE(), 1)  ;


-- tícket médio das vendas Web na semana corrente (sete dias para trás a partir do dia de ontem)
SELECT TP.DATA_COMPRA ,
		AVG(TP.VALOR_TOTAL) AS TICKET_MEDIO
FROM TB_PEDIDO TP 
WHERE TP.DATA_COMPRA BETWEEN SUBDATE(CURDATE(), 8) AND SUBDATE(CURDATE(), 1);


-- tícket médio das vendas Web no mês corrente (do dia 1 do mês corrente até o dia de ontem)
SELECT TP.DATA_COMPRA ,
		AVG(TP.VALOR_TOTAL) AS TICKET_MEDIO
FROM TB_PEDIDO TP 
WHERE TP.DATA_COMPRA BETWEEN DATE_FORMAT(CURDATE(),'%Y-%m-01') AND SUBDATE(CURDATE(), 1);



-- ranking dos produtos com quantidades mais vendidas no dia anterior
SELECT TP2.DESCRICAO_PRODUTO ,
		SUM(TI.QUANTIDADE_PRODUTO) AS QTD_TOTAL
FROM TB_NOTA_FISCAL TNF 
INNER JOIN TB_NOTA_FISCAL_ITENS TNFI ON (TNFI.NF = TNF.NF)
INNER JOIN TB_ITEM TI ON (TI.CODIGO_ITEM = TNFI.CODIGO_ITEM)
INNER JOIN TB_PRODUTO TP2 ON (TP2.CODIGO_PRODUTO = TI.CODIGO_PRODUTO)
WHERE TNF.DATA_EMISSAO = SUBDATE(CURDATE(), 1) 
GROUP BY (TP2.DESCRICAO_PRODUTO)
ORDER BY QTD_TOTAL DESC 
;



-- ranking dos produtos com quantidades mais vendidas na semana corrente (sete dias para trás a partir do dia de ontem)
SELECT TP2.DESCRICAO_PRODUTO ,
		SUM(TI.QUANTIDADE_PRODUTO) AS QTD_TOTAL
FROM TB_NOTA_FISCAL TNF 
INNER JOIN TB_NOTA_FISCAL_ITENS TNFI ON (TNFI.NF = TNF.NF)
INNER JOIN TB_ITEM TI ON (TI.CODIGO_ITEM = TNFI.CODIGO_ITEM)
INNER JOIN TB_PRODUTO TP2 ON (TP2.CODIGO_PRODUTO = TI.CODIGO_PRODUTO)
WHERE TNF.DATA_EMISSAO BETWEEN SUBDATE(CURDATE(), 8) AND SUBDATE(CURDATE(), 1)
GROUP BY (TP2.DESCRICAO_PRODUTO)
ORDER BY QTD_TOTAL DESC 
;

-- ranking dos produtos com quantidades mais vendidas no mês corrente (do dia 1 do mês corrente até o dia de ontem)
SELECT TP2.DESCRICAO_PRODUTO ,
		SUM(TI.QUANTIDADE_PRODUTO) AS QTD_TOTAL
FROM TB_NOTA_FISCAL TNF 
INNER JOIN TB_NOTA_FISCAL_ITENS TNFI ON (TNFI.NF = TNF.NF)
INNER JOIN TB_ITEM TI ON (TI.CODIGO_ITEM = TNFI.CODIGO_ITEM)
INNER JOIN TB_PRODUTO TP2 ON (TP2.CODIGO_PRODUTO = TI.CODIGO_PRODUTO)
WHERE TNF.DATA_EMISSAO BETWEEN DATE_FORMAT(CURDATE(),'%Y-%m-01') AND SUBDATE(CURDATE(), 1)
GROUP BY (TP2.DESCRICAO_PRODUTO)
ORDER BY QTD_TOTAL DESC ;


-- ranking dos produtos com valores mais vendidos no dia anterior
SELECT TP.DESCRICAO_PRODUTO ,
		SUM(TI.VALOR_TOTAL) AS VALOR_VENDIDO
FROM TB_NOTA_FISCAL TNF 
INNER JOIN TB_NOTA_FISCAL_ITENS TNFI ON (TNFI.NF = TNF.NF)
INNER JOIN TB_ITEM TI ON (TI.CODIGO_ITEM = TNFI.CODIGO_ITEM)
INNER JOIN TB_PRODUTO TP ON (TP.CODIGO_PRODUTO = TI.CODIGO_PRODUTO)
WHERE TNF.DATA_EMISSAO = SUBDATE(CURDATE(), 1) 
GROUP BY (TP.DESCRICAO_PRODUTO)
ORDER BY VALOR_VENDIDO DESC ;


-- ranking dos produtos com valores mais vendidos na semana corrente (sete dias para trás a partir do dia de ontem)
SELECT TP.DESCRICAO_PRODUTO ,
		SUM(TI.VALOR_TOTAL) AS VALOR_VENDIDO
FROM TB_NOTA_FISCAL TNF 
INNER JOIN TB_NOTA_FISCAL_ITENS TNFI ON (TNFI.NF = TNF.NF)
INNER JOIN TB_ITEM TI ON (TI.CODIGO_ITEM = TNFI.CODIGO_ITEM)
INNER JOIN TB_PRODUTO TP ON (TP.CODIGO_PRODUTO = TI.CODIGO_PRODUTO)
WHERE TNF.DATA_EMISSAO BETWEEN SUBDATE(CURDATE(), 8) AND SUBDATE(CURDATE(), 1)
GROUP BY (TP.DESCRICAO_PRODUTO)
ORDER BY VALOR_VENDIDO DESC ;

-- ranking dos produtos com valores mais vendidos no mês corrente (do dia 1 do mês corrente até o dia de ontem)
SELECT TP.DESCRICAO_PRODUTO ,
		SUM(TI.VALOR_TOTAL) AS VALOR_VENDIDO
FROM TB_NOTA_FISCAL TNF 
INNER JOIN TB_NOTA_FISCAL_ITENS TNFI ON (TNFI.NF = TNF.NF)
INNER JOIN TB_ITEM TI ON (TI.CODIGO_ITEM = TNFI.CODIGO_ITEM)
INNER JOIN TB_PRODUTO TP ON (TP.CODIGO_PRODUTO = TI.CODIGO_PRODUTO)
WHERE TNF.DATA_EMISSAO BETWEEN DATE_FORMAT(CURDATE(),'%Y-%m-01') AND SUBDATE(CURDATE(), 1)
GROUP BY (TP.DESCRICAO_PRODUTO)
ORDER BY VALOR_VENDIDO DESC ;


-- ranking dos clientes que mais compram (valor) no dia anterior
SELECT SUM(TP.VALOR_TOTAL) AS VALOR_GASTO ,
		TC.NOME_CLIENTE 
FROM TB_PEDIDO TP 
INNER JOIN TB_CLIENTE_PEDIDO TCP ON (TP.CODIGO_PEDIDO = TCP.CODIGO_PEDIDO)
INNER JOIN TB_CLIENTE TC ON (TC.CODIGO_CLIENTE = TCP.CODIGO_CLIENTE)
WHERE TP.DATA_COMPRA = SUBDATE(CURDATE(), 1) 
GROUP BY TC.NOME_CLIENTE 
ORDER BY VALOR_GASTO DESC ;


-- ranking dos clientes que mais compram (valor) na semana corrente (sete dias para trás a partir do dia de ontem)
SELECT SUM(TP.VALOR_TOTAL) AS VALOR_GASTO ,
		TC.NOME_CLIENTE 
FROM TB_PEDIDO TP 
INNER JOIN TB_CLIENTE_PEDIDO TCP ON (TP.CODIGO_PEDIDO = TCP.CODIGO_PEDIDO)
INNER JOIN TB_CLIENTE TC ON (TC.CODIGO_CLIENTE = TCP.CODIGO_CLIENTE)
WHERE TP.DATA_COMPRA BETWEEN SUBDATE(CURDATE(), 8) AND SUBDATE(CURDATE(), 1) 
GROUP BY TC.NOME_CLIENTE 
ORDER BY VALOR_GASTO DESC ;

-- ranking dos clientes que mais compram (valor) no mês corrente (do dia 1 do mês corrente até o dia de ontem)
SELECT SUM(TP.VALOR_TOTAL) AS VALOR_GASTO ,
		TC.NOME_CLIENTE 
FROM TB_PEDIDO TP 
INNER JOIN TB_CLIENTE_PEDIDO TCP ON (TP.CODIGO_PEDIDO = TCP.CODIGO_PEDIDO)
INNER JOIN TB_CLIENTE TC ON (TC.CODIGO_CLIENTE = TCP.CODIGO_CLIENTE)
WHERE TP.DATA_COMPRA BETWEEN DATE_FORMAT(CURDATE(),'%Y-%m-01') AND SUBDATE(CURDATE(), 1)
GROUP BY TC.NOME_CLIENTE 
ORDER BY VALOR_GASTO DESC ;
